### Login
POST http://localhost:8080/auth/v1/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

> {%
    client.global.set("authorizationHeaderValue", response.headers.valueOf("Authorization"));
    client.global.set("authorizationToken", response.headers.valueOf("Authorization").replace("Bearer ", ""));
%}

### Access protected service
GET http://localhost:8080/api/v1/protected
Authorization: {{authorizationHeaderValue}}

### Parse JWT in auth-service
POST http://localhost:8081/v1/jwt/parse
Content-Type: application/json

{
  "token": "{{authorizationToken}}"
}
